myFile:
  path: /docker/sell/file/
  url: http://localhost:8086/file/
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sell?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
    initialization-mode: always
  servlet:
    multipart:
     max-file-size: 10MB
     max-request-size: 10MB
     enabled: true
  jpa:
    show-sql: true
#  thymeleaf:
#    prefix: classpath:templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: false
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0 #有16个数据库，默认连接第几个
    host: localhost
    port: 6379
    #    password: zongheng    # 密码（默认为空）
    timeout: 60000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
qiniu:
  accessKey:
  secretKey:
  bucket:
  prefix:
  visitUrl: