spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://localhost:3306/sell?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      #url: jdbc:mysql://192.168.0.150/sell?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      #aliyun里的内部网络ip172.16.158.150:3306
      url: jdbc:mysql://47.99.71.179:4002/sell?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=UTF-8
      username: root
      password: 755327
      #password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
  servlet:
    multipart:
     max-file-size: 100MB
     max-request-size: 100MB
     enabled: true
  jpa:
    show-sql: true
#  thymeleaf:
#    prefix: classpath:templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    cache: false
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 2 #有16个数据库，默认连接第几个
    host: 47.99.71.179
    port: 6379
    #    password: zongheng    # 密码（默认为空）
    timeout: 60000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    view:
      prefix: classpath:templates/
      suffix: .html
    servlet:
      path: /
      load-on-startup: 1
#mybatis三剑客配置
mybatis:
  type-aliases-package: com.sell.modules.*.entity
  mapper-locations: classpath:mappers/*.xml
  #驼峰命名自动转换，打印sql语句
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
  identity: MYSQL
  not-empty: false
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
server:
  port: 8086